# Generated by Django 4.2.4 on 2023-08-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='No_of_guests',
            field=models.IntegerField(verbose_name=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Inventory',
            field=models.PositiveIntegerField(verbose_name=5),
        ),
    ]
